### ISSUE TITLE
Problem installing driver on Raspberry Pi

### ISSUE THREAD

**Issue by grodansparadis** [rusoku/TouCAN-SocketCAN#1]
Trying to install driver on Raspberry Pi (4.9.35-v7+). 'make' and 'make install' works but when I try to insert the module I get  

insmod: ERROR: could not insert module toucan.ko: Unknown symbol in module

**Comment by rusoku** [comment]
Does 'dmesg' show which symbol is missing?
Are 'can' and 'can-dev' modules loaded?
Please try:

modprobe can
modprobe can-dev
insmod toucan.ko

**Comment by grodansparadis** [comment]
Blushing... did't remember can/can-dev  works like a charm now.  Thanks!
