### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by SCarns** [rusoku/TouCAN-SocketCAN#6]
I'm getting a "Make" error when I try to compile this latest version:

pi@openplotter:~/TouCAN-SocketCAN $ sudo make
make -C /lib/modules/5.4.79-v7l+/build M=/home/pi/TouCAN-SocketCAN modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.79-v7l+'
  CC [M]  /home/pi/TouCAN-SocketCAN/toucan.o
/home/pi/TouCAN-SocketCAN/toucan.c: In function ‘toucan_rx_can_msg’:
/home/pi/TouCAN-SocketCAN/toucan.c:522:3: error: implicit declaration of function ‘can_frame_set_cc_len’; did you mean ‘skb_reset_mac_len’? [-Werror=implicit-function-declaration]
   can_frame_set_cc_len(cf, msg->dlc, priv->can.ctrlmode);
   ^~~~~~~~~~~~~~~~~~~~
   skb_reset_mac_len
/home/pi/TouCAN-SocketCAN/toucan.c:533:24: error: ‘struct can_frame’ has no member named ‘len’
   stats->rx_bytes += cf->len;
                        ^~
/home/pi/TouCAN-SocketCAN/toucan.c: In function ‘toucan_usb_probe’:
/home/pi/TouCAN-SocketCAN/toucan.c:906:12: error: ‘CAN_CTRLMODE_CC_LEN8_DLC’ undeclared (first use in this function); did you mean ‘CAN_CTRLMODE_FD_NON_ISO’?
            CAN_CTRLMODE_CC_LEN8_DLC;
            ^~~~~~~~~~~~~~~~~~~~~~~~
            CAN_CTRLMODE_FD_NON_ISO
/home/pi/TouCAN-SocketCAN/toucan.c:906:12: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:266: /home/pi/TouCAN-SocketCAN/toucan.o] Error 1
make[1]: *** [Makefile:1732: /home/pi/TouCAN-SocketCAN] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.79-v7l+'
make: *** [Makefile:6: all] Error 2

**Comment by anthrax-0** [comment]
Same error. Can we have a previous working version released as 0.9 or something like this with release notes explaining which kernel version is supported? It was quite a surprise when our systems started failing the provisioning :-(

**Comment by SCarns** [comment]
anthrax-0

My solution was to install the DKMS version. That one does install and hopefully it will survive and update.

**Comment by anthrax-0** [comment]
@SCarns At the moment we just pinned commit that was still working ;-) But DKMS kinda looks somewhat abandoned?

**Comment by rusoku** [comment]
Use tag v1.0 (release v1.0)
Latest version is for Linux version 5.15

**Comment by rusoku** [comment]
git clone --branch v1.0 https://github.com/rusoku/TouCAN-SocketCAN

**Comment by anthrax-0** [comment]
Just to clarify, for us, the working commit is basically [first](https://github.com/rusoku/TouCAN-SocketCAN/commit/1d2bc1fda9fa75b59c00231b53540dbc51cd95a8) one. As we have quite an old kernel (4.19.75)  inside RasperryPi based boxes, we can't use/update to new at the moment, so it would be good to understand what will be supported for older kernels?

**Comment by rusoku** [comment]
First commit should work with all kernel versions (5.15 and later also).Latest commits from kernel 5.15 (SocketCAN stack will be supplemented with new features)
At least it works for me.I use it with RaspberryPi, Qualcomm and Broadcom SoC's.

**Comment by anthrax-0** [comment]
That is the info that for me makes sense to have in the README together with tag for this first commit (so that it can be easily addressed and mentioned in the README as well)?

**Comment by rusoku** [comment]
I added this info to readme too

**Comment by anthrax-0** [comment]
Ah, sorry, missed this! Thank you
